import Link from 'next/link';
import { ArrowDown, ArrowUpRight, MessageCircle } from 'lucide-react';
import { getWhatsAppLink } from '@/lib/whatsapp';

export default function AboutPage() {
  return <main className="about-premium">
    <section className="about-hero"><p className="section-kicker">Our story / Nairobi, Kenya</p><h1 data-split>Quality made<br />to <span>belong here.</span></h1><div><p>Dextron Enterprise was founded with one clear intention: essential care should be dependable, accessible and made with Kenyan families in mind.</p><a href="#principles" aria-label="Read our principles"><ArrowDown /></a></div></section>
    <section className="about-statement"><p className="section-kicker">What we believe</p><h2 data-reveal>The best everyday products are never just products. They are <span>peace of mind.</span></h2></section>
    <section id="principles" className="about-principles"><p className="section-kicker">The Dextron standard</p><div>{[['01','Kenyan families first','We listen to the practical needs of caregivers and households, so every product earns its place in everyday life.'],['02','Built on uncompromising quality','Materials, performance and consistency matter. We hold every product to the standards families deserve.'],['03','Value without compromise','Local manufacturing helps bring dependable care within reach — without asking families to settle.'],['04','Growing with our communities','From shops and stockists to homes across Kenya, we build relationships that last beyond a single purchase.']].map(([n,title,copy]) => <article key={n} data-reveal><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="about-product-moment"><div data-reveal><p className="section-kicker">Made for the everyday</p><h2>Care that keeps<br />life <span>moving.</span></h2><p>From baby care and infant nutrition to feminine hygiene and home essentials, our brands are made to be the reliable part of every routine.</p><Link href="/brands">Explore our brands <ArrowUpRight /></Link></div><figure data-image-reveal><img src="/images/Nuna_Daipers_Front.jpg" alt="Nuna Diapers" /></figure></section>
    <section className="about-close"><p className="section-kicker">Work with Dextron</p><h2 data-reveal>Bring better care<br />closer to <span>your community.</span></h2><div><Link href="/distributors">Become a distributor <ArrowUpRight /></Link><a href={getWhatsAppLink('Hello Dextron Enterprise! I would like to speak with your team.')} target="_blank" rel="noopener noreferrer"><MessageCircle /> Talk to us</a></div></section>
  </main>;
}
